### ISSUE TITLE
Issue with the order of the for loops

### ISSUE THREAD

**Issue by KeiderHoyos** [ChristophReich1996/Mode_Collapse#2]
https://github.com/ChristophReich1996/Mode_Collapse/blob/72dceb5387068bff0aba5d9e7209fa3c9e9796ee/main.py#L91

I wanted to point out a small mistake regarding the for loop of the d_updates. I  believe the for loops in the main code are swapped.   "`for _ in range(args.d_updates)`" is intended to update the discriminator several times before updating the generator. However, in the code,  it is placed before "`for index in range(0, args.samples, args.batch_size)`", which is causing the discriminator to be updated int(samples/batch_size) times, and the generator just once.  

The correct order should be: 

```
for epoch in range(args.epochs):  # type: int
        # Update progress bar
        progress_bar.update(n=1)
        
        for index in range(0, args.samples, args.batch_size):  # type:int
        
            # Shuffle data
            data = data[torch.randperm(data.shape[0], device=args.device)]
            # Update discriminator more often than generator to train it till optimality 
            for _ in range(args.d_updates):  # type: int
```

**Comment by ChristophReich1996** [comment]
Hi @KeiderHoyos, thanks for pointing this out, you are completely right! Do you want to open a pull request with the fix?
